<a href="https://colab.research.google.com/github/Vyshnavichervirala/-pytorch/blob/main/basic_on_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [3]:
## introduction to tensors
#scalar
scalar=torch.tensor(8)
scalar


tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

8

In [6]:
#vector
vector=torch.tensor([8,8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX=torch.tensor([[1,2],
                      [3,4]])
MATRIX



tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([3, 4])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 6, 7]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]])

### why random tensors?
random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [17]:
#create the random tensor
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.6010, 0.6643, 0.8024, 0.6246],
        [0.4053, 0.1953, 0.7980, 0.3028],
        [0.0640, 0.5668, 0.4733, 0.7519]])

In [18]:
random_tensor.ndim

2

In [20]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
torch.rand(3,3)

tensor([[0.9099, 0.9321, 0.0553],
        [0.8646, 0.3762, 0.7120],
        [0.0907, 0.2058, 0.9304]])

# zeros and ones

In [22]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

#creating a range of tensors and tensors-like

In [27]:
#use torch.range()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor


tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])